apiVersion: v1
kind: Service
metadata:
  name: service-svc
spec:
  selector:
    app: multi-protocol-service 
  ports:
    - name: https-port
      protocol: TCP
      port: 443
      targetPort: 443
    - name: custom-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer