replicaCount: 2

image:
  repository: containerservice.azurecr.io/multi-protocol-service
  tag: latest
  pullPolicy: IfNotPresent

autoscaling:
  enabled: false  
  minReplicas: 1  
  maxReplicas: 10  
  targetCPUUtilizationPercentage: 80  

service:
  type: LoadBalancer
  ports:
    http: 80
    https: 443
    tcp: 8080

serviceAccount:
  create: true

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: protocolservices.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - protocolservices.com
      secretName: tls-secret
