apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: service.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service
            port:
              number: 443
  tls:
  - hosts:
    - service.com
    secretName: service-tls