apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-protocol-service
  labels:
    app: multi-protocol-service 
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multi-protocol-service
  template:
    metadata:
      labels:
        app: multi-protocol-service
    spec:
      containers:
        - name: multi-protocol-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080