apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-protocol-service
  labels:
    app: multi-protocol-service
    app.kubernetes.io/managed-by: Helm 
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }} 
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multi-protocol-service
  template:
    metadata:
      labels:
        app: multi-protocol-service
    spec:
      containers:
        - name: multi-protocol-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080