apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-check-error-and-rollback
spec:
  template:
    spec:
      containers:
        - name: check-error-and-rollback
          image: python:3.13
          command: ["python", "/scripts/check-error-and-rollback.py"]
          volumeMounts:
            - name: script-volume
              mountPath: /file
      volumes:
        - name: script-volume
          configMap:
            name: {{ .Release.Name }}-scripts