apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Values.component | default "unknown" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}